illdang100/tovalley

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/trip_schedule/TripScheduleRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dummy/DummyObject.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/OpenApiServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/domain/review/ReviewServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/domain/trip_schedule/TripScheduleServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/page/WaterPlaceDetailPageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/page/WaterPlaceDetailPageApiController.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/ReviewApiControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/TripScheduleApiControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/MainPageApiControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/WaterPlaceDetailPageApiControllerTest.java
-[기능 추가]
feat/waterplace-detail-page -> develop
- 물놀이 장소 상세조회 페이지 테스트 코드 작성
- 물놀이 장소별 리뷰 조회 테스트 코드 작성
- 리뷰에 대한 이미지가 함께 반환되지 않는 오류 해결
- 리뷰가 존재하지 않을 시 리뷰 평점 비율이 null로 반환되는 오류 해결
- 물놀이 장소별 여행일정 조회 테스트 코드 작성
- 존재하지 않는 물놀이 장소에 대한 여행일정 조회시 예외처리
=> 테스트 코드 작성 및 오류 해결

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/review/ReviewRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/trip_schedule/TripScheduleRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/review/ReviewReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/trip_schedule/TripScheduleRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dummy/DummyDevInit.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/review/ReviewService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/review/ReviewServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/trip_schedule/TripScheduleService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/trip_schedule/TripScheduleServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/water_place/WaterPlaceServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/ReviewApiController.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/TripScheduleApiController.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/domain/review/ReviewRepositoryImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/review/ReviewServiceImplTest.java
-[기능 추가]
ex) feat/my-page -> dev
마이페이지에서 여행 지난 일정 조회 시 리뷰 작성 여부를 응답합니다.
마이페이지에서 지난 일정에 대해 새로운 리뷰를 작성하는 기능 추가
시큐리티 설정이 마무리되면 테스트 코드 작성 예정
-> 포스트맨으로 테스트 했을 때는 잘됐음
=> 리뷰 작성 여부 응답 기능 구현 및 리뷰 작성 기능 구현

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/member/Member.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/member/MemberRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/member/MemberReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/MemberApiController.java
-[기능 추가]
feat/my-page -> dev
- 사용자 닉네임 중복확인 기능 구현
- 사용자 닉네임 변경 기능 구현
- 사용자 프로필 이미지 변경 기능 구현
- 포스트맨으로 확인했으나 추후 테스트 코드 구현 예정
=> 사용자 정보 수정 기능 구현

tovalley-react/src/App.tsx, tovalley-react/src/component/main/PopularValley.tsx, tovalley-react/src/css/valleyList/ValleyList.module.css, tovalley-react/src/page/ValleyListPage.tsx
1. 계곡 리스트 페이지, 계곡 상세페이지 연결
2. 계곡 리스트 페이지 css 수정
=> feat: valley list page connect

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/water_place/RescueSupply.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/water_place/WaterPlace.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/water_place/WaterPlaceDetail.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/form/water_place/CreateWaterPlaceForm.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/OpenApiService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/OpenApiServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/water_place/WaterPlaceServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/controller/admin/WaterPlaceController.java, tovalley-server/src/main/resources/static/css/valley-register.css, tovalley-server/src/main/resources/templates/admin/water_place/createWaterPlaceForm.html, tovalley-server/src/main/resources/templates/admin/water_place/waterPlaceDetail.html
물놀이 장소 생성 기능 구현 및 타임리페 페이지 기능 구현
물놀이 장소 상세보기 페이지에서 사건사고 정보 페이지 숫자 버그 문제 해결
-> 사건사고가 하나도 없는 경우 0페이지가 생김
=> Feat: 관리자용 새로운 물놀이 장소 생성 기능 구현 및 페이지 구현

tovalley-react/src/component/common/RatingStar.tsx, tovalley-react/src/css/user/MyPage.module.css, tovalley-react/src/page/LoginPage.tsx, tovalley-react/src/page/MyPage.tsx
=> fix: 로그인 필드명 변경

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/form/admin/LoginForm.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/security/jwt/filter/JwtAuthenticationFilter.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/security/jwt/filter/JwtAuthorizationFilter.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/controller/admin/AdminController.java, tovalley-server/src/main/resources/static/css/admin-login.css, tovalley-server/src/main/resources/templates/admin/admin-login.html
- 관리자 로그인, 로그아웃 구현
- JwtAuthorizationFilter 로그 출력 라인 삭제
=> 관리자 로그인 & 로그아웃 구현

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/water_place/WaterPlaceRepositoryCustom.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/water_place/WaterPlaceRepositoryImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/water_place/WaterPlaceReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/water_place/WaterPlaceRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/security/oauth/CustomOAuth2UserService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/water_place/WaterPlaceService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/water_place/WaterPlaceServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/MemberApiController.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/controller/admin/WaterPlaceController.java, tovalley-server/src/main/resources/static/css/admin-valley-info.css, tovalley-server/src/main/resources/templates/admin/water_place/waterPlaceList.html
Feat: 관리자 물놀이 지역 조회 페이지 구현
Fix: 자체 회원가입한 이메일과 소셜 로그인 진행한 이메일 중복될 경우 예외 처리
=> Feat: 관리자 물놀이 지역 조회 페이지 구현

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/water_place/WaterPlaceReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/security/jwt/filter/JwtAuthorizationFilter.java
- JwtAuthorizationFilter 리프레시 토큰 재발급 삭제
- AdminRetrieveWaterPlacesCondition 중복돼서 삭제
=> JwtAuthorizationFilter 리프레시 토큰 재발급 삭제

tovalley-react/public/index.html, tovalley-react/src/component/footer/Footer.tsx, tovalley-react/src/component/main/Report.tsx, tovalley-react/src/component/main/Weather.tsx, tovalley-react/src/component/main/WeatherDetail.tsx, tovalley-react/src/component/valley/calendar/AllDay.tsx, tovalley-react/src/component/valley/calendar/ControlDate.tsx, tovalley-react/src/component/valley/valleyInfo/ValleyMap.tsx, tovalley-react/src/component/valley/valleyQuality/ValleyQuality.tsx, tovalley-react/src/css/main/Accident.module.css, tovalley-react/src/css/main/PopularValley.module.css, tovalley-react/src/css/main/Report.module.css, tovalley-react/src/css/main/Weather.module.css, tovalley-react/src/css/main/WeatherDetail.module.css, tovalley-react/src/css/valley/ValleyQuality.module.css, tovalley-react/src/page/MainPage.tsx
- 지도에 날씨  아이콘 크기 축소
- 지도 지역 클릭시 상세 날씨 정보 추가
- 특보, 예비특보 토글 버튼
- 기상특보 캐러셀
- 날씨 상세정보 날씨 설명 추가
- 관리자 로그인 페이지 연결
=> feat: 메인페이지 ui 수정

tovalley-react/src/App.tsx, tovalley-react/src/axios_interceptor.tsx, tovalley-react/src/component/header/Header.tsx, tovalley-react/src/component/main/Report.tsx, tovalley-react/src/component/main/Weather.tsx, tovalley-react/src/component/user/TripSchedule.tsx, tovalley-react/src/component/user/TripScheduleItem.tsx, tovalley-react/src/component/user/WriteReview.tsx, tovalley-react/src/component/valley/valleyInfo/ValleyInfo.tsx, tovalley-react/src/css/main/Report.module.css, tovalley-react/src/css/main/Weather.module.css, tovalley-react/src/css/safetyGuide/SafetyGuide.module.css, tovalley-react/src/css/user/MyPage.module.css, tovalley-react/src/css/user/WriteReview.module.css, tovalley-react/src/css/valleyList/ValleyList.module.css, tovalley-react/src/page/MyPage.tsx, tovalley-react/src/page/SafetyGuidePage.tsx
=> feat: 안전가이드 페이지

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/review/ReviewServiceImpl.java
리뷰 작성할 때, 이미지 없으면 발생하는 문제 예외처리
=> fix: 리뷰 작성 시 발생하는 문제 예외처리

tovalley-react/public/index.html, tovalley-react/src/component/common/ConfirmModal.tsx, tovalley-react/src/component/common/RatingStar.tsx, tovalley-react/src/component/header/Header.tsx, tovalley-react/src/component/main/Accident/Accident.tsx, tovalley-react/src/component/main/PopularValley.tsx, tovalley-react/src/component/main/Report.tsx, tovalley-react/src/component/main/Weather.tsx, tovalley-react/src/component/main/WeatherDetail.tsx, tovalley-react/src/component/user/TripSchedule.tsx, tovalley-react/src/component/user/WriteReview.tsx, tovalley-react/src/component/valley/ValleyReview.tsx, tovalley-react/src/component/valley/calendar/ControlDate.tsx, tovalley-react/src/component/valley/valleyInfo/ValleyInfo.tsx, tovalley-react/src/css/main/Weather.module.css, tovalley-react/src/css/valley/ValleyPage.module.css, tovalley-react/src/page/MyPage.tsx, tovalley-react/src/page/SafetyGuidePage.tsx, tovalley-react/src/page/ValleyListPage.tsx, tovalley-react/src/page/ValleyPage.tsx
- 메인페이지 특보 버그 수정
- 리뷰 작성시 이미지 추가 버그 수정
- 계곡 상세페이지 안전안내사항 팝업 추가
- 콘솔 warning 제거중
=> fix: 버그 수정

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dummy/DummyDevInit.java
myPageDummyData() -> saveDummyData()
=> fix: 더미 데이터 오류 문제 해결

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/water_place/WaterPlaceRepository.java
물놀이 장소 "평점" 내림차순 요청
- 평점이 동일한 경우 리뷰 개수로 정렬
물놀이 장소 "리뷰 개수" 내림차순 요청
- 리뷰 개수가 동일한 경우 평점으로 정렬
=> refactor: 인기 계곡 조회 기능 리팩토링

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/review/ReviewRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/trip_schedule/TripScheduleRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dummy/DummyObject.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/CookieUtil.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/TokenUtil.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/MemberApiController.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberServiceImplTest.java
- 회원탈퇴 구현
- 쿠키 만료 메서드 CookieUtil 클래스로 이동
- 리프레시 토큰 삭제 메서드 TokenUtil 클래스로 이동
=> CH-10 회원 탈퇴

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/admin/AdminChangeRoleReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/admin/AdminChangeRoleRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/controller/admin/AdminController.java, tovalley-server/src/main/resources/templates/admin/change-role.html
- 컨트롤러 틀 잡기
- AdminChangeRoleReqDto/AdminChangeRoleRespDto 생성
=> CH-11 사용자 권한 변환 페이지

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/member/Member.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/admin/AdminChangeRoleReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/email_code/EmailCodeService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/email_code/EmailCodeServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/EmailCodeController.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/controller/admin/AdminController.java
사용자 권한 변경 틀잡기
- EmailCodeService에 메일 보내는 메서드 추가
- MemberService에 사용자 권한 변경, 리프래시 토큰 삭제 메서드 추가
=> feature: 사용자 권한 변경 기능 구현

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoard.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardImage.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardImageRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepositoryCustom.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepositoryImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundEnum.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/water_place/WaterPlaceRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dummy/DummyObject.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardController.java, tovalley-server/src/main/resources/db/schema.sql, tovalley-server/src/main/resources/db/teardown.sql, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepositoryImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardControllerTest.java
- 분실물 조회 페이지 구현 (service, repository, controller)
- 분실물 조회 repository 단위 테스트 구현
=> CH-23 분실물 조회 페이지 기능 구현

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/TokenUtil.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/MemberApiControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/ReviewApiControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/TripScheduleApiControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/LostFoundBoardControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/MyPageApiControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/WaterPlaceDetailPageApiControllerTest.java
- 테스트 코드 버그 해결: 로그인 실패 에러
- 액세스 토큰을 쿠키에 담아서 테스트 수행하도록 수정
- TokenUtil에 테스트용 액세스 토큰 생성 메서드 생성
=> CH-37 인증 관련 (테스트 코드) 버그 해결

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/FileRootPathVO.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/S3Service.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardImageService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardImageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/ListUtil.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardController.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/LostFoundBoardControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/TripScheduleApiControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/LostFoundBoardControllerTest.java
- 게시글 작성 리포지토리, 서비스, 컨트롤러 로직 구현
- s3Service 여러 파일 업로드 메서드 생성
- 게시글 작성 컨트롤러 테스트 코드 구현
=> CH-32 분실물 게시글 등록 기능 구현

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoard.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardImageRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dummy/DummyObject.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardImageService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardImageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/page/PageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/EntityFinder.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/ImageUtil.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/ListUtil.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardController.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepositoryImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/page/LostFoundBoardServiceImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/LostFoundBoardControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/LostFoundBoardControllerTest.java
- 분실물 게시글 수정 구현
- 컨트롤러, 서비스 테스트 코드 작성
=> CH-33 분실물 게시글 수정

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/page/PageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/EntityFinder.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/page/LostFoundBoardServiceImplTest.java
- LostFoundBoard 조회할 때 WaterPlace와 fetch join 걸어서 조회하기
- 게시글 상세 응답 dto에 분실물 작성자 프로필, 계곡 이름, 계곡 주소, 내 글인지 여부, 댓글 아이디 추가
=> CH-40 분실물 게시글 상세 수정

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardReqDto.java
- valleyId 리스트 @NotEmpty 어노테이션 제거
=> CH-51 분실물 게시글 조회 수정

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoard.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardImageRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardImageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/page/PageService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/page/PageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/util/EntityFinder.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardController.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/PageApiController.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/page/LostFoundBoardServiceImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/LostFoundBoardControllerTest.java
- 게시글 해결 완료 상태 변경 (서비스, 컨트롤러, 테스트코드) 구현
- findLostFoundBoardOrElseThrowEx 메서드 생성
- findLostFoundBoardByIdWithMemberOrElseThrowEx 메서드명 변경
=> CH-41 분실물 게시글 해결 완료 체크

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/comment/Comment.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoard.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardImage.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardController.java, tovalley-server/src/main/resources/db/schema.sql, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/member/MemberServiceImplTest.java
- 분실물 게시글 수정, 게시글 해결 완료 상태 변경 시 게시글 작성자가 아닌 사용자일 경우 예외 발생
- 작성자 외 요청 경우 테스트 코드 작성(게시글 수정, 게시글 해결 완료 상태 변경)
=> CH-43 분실물 게시글 기능

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepositoryImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardReqDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/comment/CommentService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/comment/CommentServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardImageService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardImageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardController.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImplTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/LostFoundBoardControllerTest.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/LostFoundBoardControllerTest.java
- 게시글 이미지 삭제 로직
- 게시글 댓글 삭제 로직
- 게시글 삭제 로직
- 게시글 작성자 외 접근 시 예외 처리 로직 공통화
- 닉네임 저장 여부 로직 리팩토링 (추후에 소셜로그인 시 닉네임 임의 저장되도록 구현할 예정)
=> feat: 분실물 게시글 삭제 구현 

tovalley-react/src/page/LostItemPostPage.tsx, tovalley-react/src/page/LostItemUpdatePage.tsx, tovalley-react/src/typings/db.ts
- 분실물 게시글 수정 field 추가
- 상세페이지 댓글 없을 시 에러 처리
- 해결 체크 에러 수정
- 댓글 작성시 예외 처리
=> fix: 분실물 게시글 수정

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepositoryCustom.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepositoryImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/page/PageRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dummy/DummyObject.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/page/PageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardController.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/web/page/MyPageApiControllerTest.java
마이 페이지 - 내 게시글 목록 조회 기능 구현
- 마이 페이지 응답 Dto 필드로 내 게시글 목록(Slice<MyLostFoundBoardRespDto> myLostFoundBoards) 필드 추가
- 내 게시글 목록 조회 컨트롤러 메서드 추가
=> 마이 페이지 - 내 게시글 목록 조회 기능 구현

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/lost_found_board/LostFoundBoardRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/domain/review/ReviewRepository.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/lost_found_board/LostFoundBoardRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/page/PageRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/review/ReviewRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/lost_found_board/LostFoundBoardServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/page/PageService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/page/PageServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/review/ReviewService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/review/ReviewServiceImpl.java, tovalley-server/src/test/java/kr/ac/kumoh/illdang100/tovalley/domain/review/ReviewRepositoryImplTest.java
- 가장 최근 3개 리뷰, 분실물 게시글 조회해서 메일 페이지 요청의 응답에 추가함
=> feat: 홈페이지 - 최근 리뷰, 최근 분실물 게시글 

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/config/chat/WebSocketConfig.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/dto/chat/ChatRespDto.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/chat/ChatService.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/service/chat/ChatServiceImpl.java, tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/ChatApiController.java
- 채팅방 목록 조회 시 사용자 닉네임 추가 반환
- WebSocket 전송 설정 구성
- 메시지 최대 크기: 512KB, 메시지 전송 시간 제한: 10초, 전송 버퍼 사이즈: 512KB
=> 웹소켓 전송 설정 구성 및 채팅방 목록 조회 시 사용자 닉네임 추가 반환

tovalley-server/src/main/java/kr/ac/kumoh/illdang100/tovalley/web/api/LostFoundBoardApiController.java
- 삭제되거나 새로 등록할 이미지가 없는 경우를 위해 empty인지 검사하는 로직 추가함
=> fix: 분실물 커뮤니티 게시글 수정 - 이미지 삭제 및 추가 에러 해결

tovalley-react/src/axios_interceptor.tsx, tovalley-react/src/component/common/Alarm.tsx, tovalley-react/src/component/common/AlarmList.tsx, tovalley-react/src/component/header/Chat.tsx, tovalley-react/src/component/header/ChatComponent.tsx, tovalley-react/src/component/header/Header.tsx, tovalley-react/src/component/valley/ValleyReview.tsx, tovalley-react/src/css/common/Alarm.module.css, tovalley-react/src/css/header/ChatComponent.module.css, tovalley-react/src/css/lostItem/LostItemList.module.css, tovalley-react/src/css/user/MyPage.module.css, tovalley-react/src/page/MyPage.tsx, tovalley-react/src/page/ValleyPage.tsx, tovalley-react/src/store/chat/chatRoomNameSlice.ts, tovalley-react/src/store/store.ts, tovalley-react/src/typings/db.ts
- 채팅 메시지 조회 중 새로운 메시지 왔을 때 하단에 띄우기
- 채팅 메시지 readCount 버그 수정
- 헤더 알림 아이콘 new 표시
- 채팅 메시지 사진 전송 구현, 이미지 메시지 띄우기
- 이미지 메시지 알림 처리
- 채팅 메시지 조회 버그 수정
- 채팅 목록과 채팅방 닉네임 표시
- 마이페이지 내 글 연결
- 계곡 상세페이지 내 리뷰일 때 채팅 아이콘 삭제
- 다른 IP 접근 401 에러 핸들링
=> feat: 채팅 기능 구현, 마이페이지 내 글 연결

tovalley-react/src/component/header/ChatComponent.tsx, tovalley-react/src/component/header/Header.tsx, tovalley-react/src/page/LostItemPostPage.tsx, tovalley-react/src/page/LostItemWritePage.tsx
- 분실물 글 작성 시 주소찾기 버튼 삭제
- 분실물 게시글 댓글 작성 버그 수정
- 채팅 시간 버그 수정
- 채팅 엔터키로 전송 (이미지는 안됨)
- 채팅 readCount 버그 수정
=> fix: 채팅 및 분실물 커뮤니티 버그 수정
